name: Waka Readme

on:
  schedule:
    - cron: '30 18 * * *'  # Runs at 12:30 AM IST daily
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest

    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"        # Disables OS usage stats
          SHOW_PROJECTS: "False"  # Disables project stats
          SHOW_LANGUAGES: "True"  # Shows language stats
          SHOW_CODE_TIME: "True"  # Shows total coding time
          SHOW_LINES_OF_CODE: "False"  # Disables lines of code stats
