name: Waka Readme

on:
  schedule:
    - cron: '30 18 * * *'  # Scheduled daily at 12:30 AM IST
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE: "True"  # Enable language stats
          SHOW_LINES_OF_CODE: "False"  # Disable lines of code for performance
          SHOW_TOTAL_CODE_TIME: "True"  # Enable total code time
          SHOW_PROFILE_VIEWS: "True"
